### ISSUE TITLE
please add "Delegators amount" to api - validator/<validator_address>

### ISSUE THREAD

**Issue by bro-n-bro-99** [bro-n-bro/bro.app#111]

**Comment by bro-n-bro-2** [comment]
@prevetal , please add voting_power from /validators/cosmosvaloper196ax4vc0lwpxndu9dyhvca7jhxp70rmcvrj90c 
to total delegated amount
![image](https://github.com/bro-n-bro/bro.app/assets/89855562/cfee1625-c328-4fcb-968c-9d905a678141)
