### ISSUE TITLE
Proposal page with empty proposals

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro.app#114]
![image](https://github.com/bro-n-bro/bro.app/assets/89855562/3190d996-0bb3-4be0-acac-a45f5a093543)
Please, add a picture and text/description
 **Seems like, there is no proposal in such status**

**Comment by bro-n-bro-99** [comment]
suggested text to display
Currently, there are no proposals to display. We appreciate your interest and look forward to your votes in the future.

**Comment by bro-n-bro-99** [comment]
@prevetal

**Comment by bro-n-bro-99** [comment]
@irahunt I think we need to work on visual for this first, for you reference text is above

**Comment by bro-n-bro-2** [comment]
![image](https://github.com/bro-n-bro/bro.app/assets/89855562/20cfccb5-22b4-43ee-b847-92d3c151a4a0)
