### ISSUE TITLE
Add percent of validator delegators votes to UI

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro.app#115]
![image](https://github.com/bro-n-bro/bro.app/assets/89855562/9ca91c24-b594-4d4f-be57-8577f95922ff)
Range 0.01 - 100

**Comment by prevetal** [comment]
@bro-n-bro-0 
The response requires information for each validator about its total amount or total shares

**Comment by bro-n-bro-2** [comment]
Let's discuss it on call. We need to adjust API response. I thought we had such info in response :(
The main goal to show delegators_shares_options in total/validator_tokens_amount
To see community engagement for each validator.

**Comment by bro-n-bro-2** [comment]
@iljagrabar14 @bro-n-bro-0 , could you please add voting power to /gov/votes/{id}/validators-info ?

**Comment by bro-n-bro-2** [comment]
https://www.figma.com/file/qhmlIKVNDNUFfdkOZqhvnR/%F0%9F%91%8A%F0%9F%8F%BB-bro_n_bro-team?type=design&node-id=4710-78095&mode=design&t=m7KDWQpdLooct9JO-4

**Comment by bro-n-bro-99** [comment]
@prevetal 

last column name - Participation Rate

also please add the same (i) tooltip to it with an explanation "Percentage of voters relative to the total number of delegators."

**Comment by bro-n-bro-2** [comment]
Align right percents
