### ISSUE TITLE
Design an option if community didn't vote

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro.app#120]
![image](https://github.com/bro-n-bro/bro.app/assets/89855562/3553cc7c-3339-48a1-9ef6-a4cf71f58883)

It can be just a text or some graphical option.

**Comment by irahunt** [comment]
https://www.figma.com/file/qhmlIKVNDNUFfdkOZqhvnR/%F0%9F%91%8A%F0%9F%8F%BB-bro_n_bro-team?type=design&node-id=7914-113654&mode=design&t=ZcvyXbJuW0xueNE5-4
