### ISSUE TITLE
Create a "suspicious" badge near airdrop proposals

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro.app#126]
Create a "suspicious" badge near airdrop proposals for preview and full view

**Comment by bro-n-bro-2** [comment]
https://www.figma.com/file/qhmlIKVNDNUFfdkOZqhvnR/%F0%9F%91%8A%F0%9F%8F%BB-bro_n_bro-team?type=design&node-id=8197-148412&mode=design&t=5rmpVywDTS9an92c-0

**Comment by irahunt** [comment]
update — https://www.figma.com/file/qhmlIKVNDNUFfdkOZqhvnR/%F0%9F%91%8A%F0%9F%8F%BB-bro_n_bro-team?type=design&node-id=8197-149720&mode=design&t=7JpgRbBGSAAZ61yy-4
@prevetal
