### ISSUE TITLE
Bug hunting before beta release

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/bro.app#21]
draft here:
https://hackmd.io/lATFJGG1ReWrTpQWMLW9uQ

- [x] Dropdown menu with currency selected is not hiding after selection

**Comment by bro-n-bro-2** [comment]
![image](https://user-images.githubusercontent.com/89855562/194316499-ac94bd4e-7b36-4628-b139-b67f58eb3b48.png)
Redelegate module. When you click on dropdown button, section doesn't disappear.
