### ISSUE TITLE
Delegation on Desmos Network Fails

### ISSUE THREAD

**Issue by flarnrules** [bro-n-bro/bro.app#34]
I'm currently using Brave Browser on a Windows 11 operating system.

When I try to delegate to the bro_n_bro delegator on the bro_app the delegation fails. I have enough available Desmos tokens to delegate and get the following error:

"The transaction has been rejected"

I've tried a few times and continue to get this error.

**Comment by bro-n-bro-0** [comment]
Hey @flarnrules !
Thanks for the report! 

Can you also provide a console log if possible?

**Comment by flarnrules** [comment]
I don't know how to do that. I would be happy to do that but I'd need
someone to explain how to do that / what that means.

Regards.

**Comment by bro-n-bro-99** [comment]
okay, no worries

to open console log in Brave browser please press Command+Option+J (Mac) or Control+Shift+J (Windows, Linux, Chrome OS) and perform your transaction one more time so it could show Rejected reason and we can dig into this issue, you can provide printscreen or whatever is convinient for you

also another question, are you performing this transcation through ledger? 

regards!

**Comment by bro-n-bro-99** [comment]
hey @flarnrules, any updates?

**Comment by flarnrules** [comment]
Hi!

I took a picture of my console log. I get a ton of errors when the webpage
loads, but the error that I get when I try to delegate to desmos looks like
this:

[image: image.png]

All of the errors look like this:

[image: Screenshot 2022-11-21 133625.png]

Hope that helps! Keep up the great work.

Ben

**Comment by altbro** [comment]
> 

Hi mate! 
please re-upload your sreenshots!

**Comment by flarnrules** [comment]
[image: Screenshot 2022-11-21 133625.png]

**Comment by bro-n-bro-99** [comment]
@flarnrules still not visible :( 

could you please send it to our telegram chat? 
https://t.me/bro_n_bro_community

**Comment by flarnrules** [comment]
Weird... Well I can type it out: I don't have telegram right now.

==

Error: Unsupported type:
'/desmos.profiles.v1beta1.Profile'
  at k.c [as accountParser] (accounts.ts:87:13)
  at k.getAccount (stargateclient.ts:24:29)
  at async k.getSequence (stargateclient.ts:254:11)
  at async k.simulate (signingstargateclient.ts:174:13)
  at async h (ManageModal.vue:413:33)

==

**Comment by flarnrules** [comment]
Keplr extension with no ledger.

**Comment by bro-n-bro-99** [comment]
Hi mate @flarnrules 

could you please check it now if it gives you any error?

**Comment by flarnrules** [comment]
Got an error again...

Error: Unsupported type: '/desmos.profiles.v1beta1.Profile'
    at k.c [as accountParser] (accounts.ts:87:13)
    at k.getAccount (stargateclient.ts:244:29)
    at async k.getSequence (stargateclient.ts:254:11)
    at async k.simulate (signingstargateclient.ts:174:13)
    at async h (ManageModal.vue:413:33)

Hope that helps. I also removed Desmos chain from my wallet and then added
it back to see if that might work. It didn't work.

Thanks

**Comment by bro-n-bro-99** [comment]
Hi @flarnrules 

have you did any recent keplr updates? and if the issue still appears on your side? as we do not get any messages with this error

thanks!

**Comment by flarnrules** [comment]
I'll try again tonight! I'm currently traveling but I'll have access to my
computer later. Fingers crossed.

**Comment by bro-n-bro-99** [comment]
Unfortunately, we cannot repeat the error that appeared on your part, and since there is no feedback we assume that the problem has been resolved. In the event of a recurrence, please let us know and we will reconsider the issue.
