### ISSUE TITLE
Refactor delegate/redelegate modal window

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/bro.app#39]
> On the Delegate tab, I’d remove the “Validator to delegate -> Bro n Bro”. We cant change this option anyway, so no option making the UX longer. Instead, tchange the title of the “Amount to Delegate” box to “Amount to Delegate to Bro & Bro”

**Comment by bro-n-bro-2** [comment]
Add description on delegate "Stake with your Bro to unlock all bro app features"
Claim button, Claim all and Compound.
Restake buttons.
