### ISSUE TITLE
Add  a possibility to open  modal windows  by URL

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro.app#48]
Add  a possibility to open  modal windows  by URL and link them with bro site

**Comment by Braiteck** [comment]
Add to url param "manage_modal=evmos"

Where "evmos" it's chain name from vue storage

Available networks
cosmoshub, bostrom, osmosis, juno, emoney, stargaze, gravity, evmos, crescent, omniflix, desmos,  stride
