### ISSUE TITLE
Find or develop a tokens registry

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/bro.app#5]
The proposed structure is: 

```json
[
   {
      "network": "network_name",
      "tokens": [
         {
            "ibc_denom": "ibc123",
            "native_denom": "utoken"
         },
      ]
   },
]
```

**Comment by bro-n-bro-2** [comment]
https://github.com/osmosis-labs/assetlists/blob/main/osmosis-1/osmosis-1.assetlist.json

``https://lcd.osmosis-1.bronbro.io/cosmos/bank/v1beta1/balances/osmo1tqdvlku97p88z5ndf3jz55vnccmzgs8jla375r``

`` {
      "denom": "ibc/1DC495FCEFDA068A3820F903EDBD78B942FBD204D7E93D3BA2B432E9669D1A59",
      "amount": "101191132"
    },
``

``https://lcd.osmosis-1.bronbro.io/ibc/apps/transfer/v1/denom_traces/1DC495FCEFDA068A3820F903EDBD78B942FBD204D7E93D3BA2B432E9669D1A59``

``{
  "denom_trace": {
    "path": "transfer/channel-37",
    "base_denom": "ungm"
  }
}
``

**Comment by bro-n-bro-0** [comment]
Check-out for all APIs

- [x] [evmos](https://lcd.evmos-9001-2.bronbro.io/ibc/apps/transfer/v1/denom_traces/11E3CF372E065ACB1A39C531A3C7E7E03F60B5D0653AD2139D31128ACD2772B5)
- [x] [juno](https://lcd.juno-1.bronbro.io/ibc/apps/transfer/v1/denom_traces/11E3CF372E065ACB1A39C531A3C7E7E03F60B5D0653AD2139D31128ACD2772B5)
- [x] [cosmoshub](https://lcd.cosmoshub-4.bronbro.io/ibc/apps/transfer/v1/denom_traces/03FDDDFA51B58B17520629DD2082A9D8B2D72FA06BD060E660006ACF9D9AF58C)
- [x] [bostrom](https://lcd.bostrom.bronbro.io/ibc/apps/transfer/v1/denom_traces/13B2C536BB057AC79D5616B8EA1B9540EC1F2170718CAFF6F0083C966FFFED0B)
- [ ] [emoney](https://lcd.emoney-3.bronbro.io/ibc/apps/transfer/v1/denom_traces/10E2FD6A073F2746143FFF978B61C3813B773CBC0647E850A4A562FFFA8F9732)
- [x] [desmos](https://lcd.desmos-mainnet.bronbro.io/ibc/apps/transfer/v1/denom_traces/13B2C536BB057AC79D5616B8EA1B9540EC1F2170718CAFF6F0083C966FFFED0B)
- [x] [osmosis](https://lcd.osmosis-1.bronbro.io/ibc/apps/transfer/v1/denom_traces/1DC495FCEFDA068A3820F903EDBD78B942FBD204D7E93D3BA2B432E9669D1A59)
- [x] [crescent](https://lcd.crescent-1.bronbro.io/ibc/apps/transfer/v1/denom_traces/0634D0993744740D675AD01E81156EAC945AEAAE17C074918DC7FF52F41B263E)
- [x] [g-bridge](https://lcd.gravity-bridge-3.bronbro.io/ibc/apps/transfer/v1/denom_traces/00F2B62EB069321A454B708876476AFCD9C23C8C9C4A5A206DDF1CD96B645057)
- [x]  [stargaze](https://lcd.stargaze-1.bronbro.io/ibc/apps/transfer/v1/denom_traces/0E57658B71E9CC4BB0F6FE3E01712966713B49E6FD292E6B66E3F111B103D361)
- [ ] Omniflix ???
- [x] [stride](https://lcd.stride-1.bronbro.io/ibc/apps/transfer/v1/denom_traces/A3643FAA80C7DA7E72B23853340F6EAD4F3A698CDC39CE42FBF23F3A4A6E3803)
