### ISSUE TITLE
design main charts page

### ISSUE THREAD

**Issue by bro-n-bro-99** [bro-n-bro/bro.app#57]

**Comment by bro-n-bro-0** [comment]
The logic for the passport stats in one defined network is: 

1. Get passport addresses (passport address included)
2. Convert to `prefix` addresses (except evmos and desmos) 
3. For all addresses get balances 
4. 
![image](https://user-images.githubusercontent.com/89854952/235727009-9e164697-9701-4c6b-801c-bdc57d1822ce.png)
4.1 Staked tokens as the sum of staked in the API 
4.2 Liquid tokens as the sum of liquid atom tokens and rewards tokens in the API
4.3 Unbonding tokens as sum of unbending tokens 
5. 
<img width="734" alt="image" src="https://user-images.githubusercontent.com/89854952/235728028-f80c638a-2a4b-439b-b202-d61aa511ab13.png">
5.1 All liquid tokens in the liquid field plus commission grouped by denom
6.
<img width="719" alt="image" src="https://user-images.githubusercontent.com/89854952/235728323-7f38b997-d65c-4286-a75f-96ed4da209d4.png">
6.1 All tokens grouped by denom
7. 
<img width="729" alt="image" src="https://user-images.githubusercontent.com/89854952/235728554-257cb5d1-fee1-4dea-94e3-5e944ddd2557.png">
7.1 All tokens valuation
8.
<img width="746" alt="image" src="https://user-images.githubusercontent.com/89854952/235728794-39a9a4e7-3196-4c65-a798-14ddb0923c88.png">
8.1 All tokens valuation grouped by address


*Each token in the API has its price in USD and exponent. To get USD valuation
`amount / 10ˆexponent / price`. To get valuation in BTC, ETH and ATOM, just query the price from price feed API
