### ISSUE TITLE
account indicators description

### ISSUE THREAD

**Issue by bro-n-bro-99** [bro-n-bro/bro.app#80]

**Comment by bro-n-bro-0** [comment]
![image](https://github.com/bro-n-bro/bro.app/assets/89854952/d84de412-628d-46e9-8b9a-d41f0bbd60d8)

APR.
1. If 1 acc and 1 network were chosen get the apr value from account_info API, else get the sum of all annual_provision amounts converted to USD, and get all staked amounts converted to USD and divide annual_provision/staked. There is apr in shares, to get in % multiply to 100

VOTING POWER
This is only the sum of voting powers in the account_info endpoint

PASSPORT VALUE
The sum of all tokens converted to USD

RPDE
The sum of RPDEs from all accounts converted to USDT
